### ISSUE TITLE
Unable to map port 443 to port 80

### ISSUE THREAD

**Issue by marten-der-Eisbaer** [fkie-cad/TLExport#3]
When trying to map port 443 to port 80 the following error occurs:
```
WARNING: Wireshark is installed, but cannot read manuf !
[*] Using keys from SSLKEYLOG: .\keylog.txt
[*] Checking for TLS traffic on these ports: [443, 44330, 443]
[*] Decrypting session: [139.162.123.134:443-172.27.146.253:49920]

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\larsm\AppData\Local\Programs\Python\Python312\Scripts\tlexport.exe\__main__.py", line 7, in <module>
  File "C:\Users\larsm\AppData\Local\Programs\Python\Python312\Lib\site-packages\tlexport\main.py", line 265, in run
    all_decrypted_sessions.extend(session.decrypt())
                                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\larsm\AppData\Local\Programs\Python\Python312\Lib\site-packages\tlexport\session.py", line 287, in decrypt
    self.builder = OutputBuilder(self.application_traffic, self.binary_to_ip(self.server_ip).__str__(), self.binary_to_ip(self.client_ip).__str__(), self.server_port,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\larsm\AppData\Local\Programs\Python\Python312\Lib\site-packages\tlexport\output_builder.py", line 33, in __init__
    print(f"[*] Writing decrypted session to new destination ports (orignal:new): {self.portmap}")
                                                                                   ^^^^^^^^^^^^
AttributeError: 'OutputBuilder' object has no attribute 'portmap'
```

[The pcap file in question](https://github.com/user-attachments/files/16646279/pcap-file.zip)

**Comment by WithLab** [comment]
The reason this error occurs is, because ```self.portmap``` is never declared. ```output_builder.py``` only uses the parameter ```portmap``` given in the init. The commit cd78ca4 should have solved this issue.
